FROM bitnami/kafka:latest

# KRaft mode configuration
ENV KAFKA_CFG_NODE_ID=1
ENV KAFKA_CFG_PROCESS_ROLES=controller,broker
ENV KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
ENV KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
ENV KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
ENV KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_KRAFT_CLUSTER_ID=L69nrXzHSvCcXf8Y2yMv8A
ENV ALLOW_PLAINTEXT_LISTENER=yes

EXPOSE 9092 9093
